version: '3.7'

services:  
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: sh -c "python beauty/manage.py makemigrations && python beauty/manage.py migrate && python beauty/manage.py runserver 0.0.0.0:8000"
    depends_on: 
      - db
    env_file:
      - .env

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=beauty
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - django_db:/var/lib/postgresql/data

volumes:
  django_db:
